#!/bin/bash

### BEGIN INIT INFO
# Provides:          flamehaze
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      1
# Short-Description: start flamehaze
### END INIT INFO

. /etc/default/flamehaze

start_service() {
	if [ -f $FLAMEHAZE_PID_FILE ]
	then
		pid=$(cat $FLAMEHAZE_PID_FILE)
		if [ -d /proc/$pid ]
		then
			echo Already Running \(pid: $pid\)
			exit 1
		else
			rm $FLAMEHAZE_PID_FILE
		fi
	fi

	pid=$(sudo -E -H -u $FLAMEHAZE_USER /bin/bash -c 'python /usr/bin/flamehaze >/dev/null &
			echo $!')

	if [ "$pid" = "" ]
	then
		echo Starting flamehaze failed
		exit 1
	fi

	echo $pid > $FLAMEHAZE_PID_FILE
	echo Starting flamehaze on PID $pid
}

stop_service() {
	if [ -f $FLAMEHAZE_PID_FILE ]
	then
		pid=$(cat $FLAMEHAZE_PID_FILE)
		if [ -d /proc/$pid ]
		then
			echo Stopping flamehaze
			kill -9 $pid
			rm $FLAMEHAZE_PID_FILE
			exit 0
		else
			echo PID file exists\, but process not running
			echo Removing PID file
			rm $FLAMEHAZE_PID_FILE
			exit 1
		fi
	fi

	echo Flamehaze not running
	exit 1
}

display_status() {
	if [ -f $FLAMEHAZE_PID_FILE ]
	then
		pid=$(cat $FLAMEHAZE_PID_FILE)

		if [ -d /proc/$pid ]
		then
			echo Flamehaze running \( pid: $pid \)
		else
			echo Flamehaze: pid file exists, but not running \( pid: $pid \)
		fi
	else
		echo Flamehaze not running
	fi
}

case "$1" in
	start)
		start_service
		;;
	stop)
		stop_service
		;;
	restart)
		stop_service
		start_service
		;;
	status)
		display_status
		;;
	*)
		echo usage: $0 "{start|stop|restart}"
		exit 1
esac	
